### ISSUE TITLE
external bandwidth limits on Vercel Blob.....

### ISSUE THREAD

**Issue by jackgofff** [Pondorasti/emojis#19]
Do you recommend leaving Vercel Blob for a different (cheaper) solution?  Is caching the issue and/or is a stronger CDN needed?

Tried running this myself:
**- 211 emojis generated 
-  466MB Outgoing Bandwidth 🤯🤯🤯**

<img width="1083" alt="image" src="https://github.com/Pondorasti/emojis/assets/141548271/8bafd327-7d94-4562-b38c-b87463ca0856">

<img width="726" alt="image" src="https://github.com/Pondorasti/emojis/assets/141548271/029f8dcc-39aa-4b76-bd7e-48edb599faa0">

**Comment by jackgofff** [comment]
Let me know @Pondorasti  ! 🙏

**Comment by pondorasti** [comment]
You can find more details on the [Vercel Blob Pricing](https://vercel.com/docs/storage/vercel-blob/usage-and-pricing) page. Right now there will be no additional charges on over-usage while the product is in beta. 

It's true that this project will kick-in over-usage on additional bandwidth almost immediately. While Vercel Blob will have a premium over S3 and most likely not be as cheap, I expect the upcoming price release to be competitive. At the moment, I have no intention of porting over the project to a different storage provider and I'm happy with Vercel.

Hope this helped, let me know if you have any other questions @jackgofff 🙌

**Comment by jackgofff** [comment]
@Pondorasti  thanks for the reply! I read the [Vercel Blob Pricing ](https://vercel.com/docs/storage/vercel-blob/usage-and-pricing) page but it was mostly general tips..... 

I'm using the template you have but not for emojis (for my own fine-tuned Replicate SDXL model  on logos). 
- If you don't mind, how much $$$ is the website (with the current amount of traffic) costing you?
- Could share any strategies (see below) you're implementing to maintain it? 

<img width="557" alt="image" src="https://github.com/Pondorasti/emojis/assets/141548271/0139141b-0133-4172-98d2-89ec92ceb6d4">


 ( _Btw: I sent you an email from **fdlstx@skiff.com** so feel free to reply back there if this Git Issue is getting too cluttered 😊_ )

**Comment by pondorasti** [comment]
Sure, here's my Vercel Blob breakdown. Again, I'm not paying anything for over usage at the moment since the product is in beta. I also don't know what the pricing is going to be, so I don't have any estimates for a cost breakdown. It's just the $20 for the Pro plan.

![CleanShot 2023-10-12 at 22 33 54](https://github.com/Pondorasti/emojis/assets/32957606/cc7118ff-9ff7-4e3d-83b2-509c7b05d5d4)

Regarding optimizations, I didn't do much besides immediately disabling image optimizations. After, the first day the bill was already at $630 and immediately disabled them.

![CleanShot 2023-10-12 at 22 36 55](https://github.com/Pondorasti/emojis/assets/32957606/e690858c-f75f-4452-9dd4-02ba3116f883)

Lastly, I pay $59/month for the PS-20 Scaler on PlanetScale. Anything bellow that with my traffic makes the P75 queries really slow and also maxes connection pooling.

![CleanShot 2023-10-12 at 22 38 20](https://github.com/Pondorasti/emojis/assets/32957606/77e8b33b-2d03-4957-8659-857f02e42cc7)


Besides disabling image optimizations, I would say not to worry too much about it at least at the beginning of the project. If you are really worried about this stuff just use S3 and call it a day, but the iteration speed with Blob was unbeatable for me.
